# _config.yml

title: "Vishrut Bezbarua"
theme: jekyll-theme-minimal
description: "I am a Data Scientist and an Astrophysicist, assymmetrically interested in Machine Learning and Artificial Intelligence with half a decade of experience in Python programming. Apart from painting, singing and occassionally hitting the gym, I have a specific range of topics I like to read about (Cybersecurity, evolutionary biology/psychology, ancient history and political science, but I like it the most when some of them converge.)."
logo: "/assets/492ee05d-735b-465f-9788-2011cc43f7db-modified.png"
